#+title: Kirols Bakheat Resume
#+author: Kirols Bakheat

#+include: ./helper.org

#+latex_header_extra: \newcommand{\githubUser}{kero0}
#+latex_header_extra: \newcommand{\linkedinUser}{kirols}
#+latex_header_extra: \newcommand{\email}{kbakheat@gmail.com}
#+latex_header_extra: \newcommand{\phone}{248-250-3241}

#+latex_header_extra: \newcommand{\header}{Innovative Software Engineer with a strong background in computer science, electrical engineering, and applied research. Skilled in embedded systems, machine learning, and full-stack development, with proven success in developing algorithms, debugging complex systems, and leading cross-functional programs. Adept at solving challenging technical problems, deploying scalable solutions, and driving projects from concept to launch. Strong foundation in both software and hardware engineering.}

* Experience
{{{experience-start(Software Engineer - Infotainment Systems *|* Ford Motor Company,March 2024 -- Present)}}}
- Diagnose and resolve performance issues in Android-based infotainment systems, including crashes, black screens, and unresponsive apps.
- Debug and deliver fixes for Android core components, contributing patches upstream.
- Develop and implement methods to dynaimcally estimate vehicle parameters for energy based vehicle routing.
- Implement platform-level Android code to optimize in-vehicle energy and performance.
{{{experience-end}}}

{{{experience-start(Research Engineer - Sensors and Algorithms *|* Ford Motor Company,July 2023 -- March 2024)}}}
- Engineered high-accuracy 3D driver positioning system for AR applications using multi-camera setups, additional sensors, and ML models.
- Designed and executed precision test plans achieving sub-millimeter accuracy in 3D eye tracking.
{{{experience-end}}}

{{{experience-start(Program Manager - Super Duty *|* Ford Motor Company,March 2023 -- July 2023)}}}
- Successfully launched 2023MY & 2024MY Super Duty trucks by managing issue resolution and launch readiness.
- Oversaw diagnostic trouble codes (DTCs), ensuring accountability and timely fixes across engineering teams.
- Improved issue tracking workflows to accelerate pre-launch problem resolution.
{{{experience-end}}}

{{{experience-start(Research Engineer - Core AI/ML/QC *|* Ford Motor Company,September 2022 -- February 2023)}}}
- Conducted pioneering research on neuromorphic computing with Intel’s Loihi platform.
- Developed an energy-optimized routing algorithm for real-world Ford service applications.
- Built and deployed a cloud service on GCP, including architecture design, CI/CD pipelines, backend, and frontend integration.
- Benchmarked accuracy, efficiency, and performance across neuromorphic, classical, and quantum computing paradigms.
{{{experience-end}}}

{{{experience-start(Research Intern - IoT *|* Ford Motor Company,May 2021 -- July 2021)}}}
- Built a proof-of-concept IoT API microservice, prototyped locally and in the cloud.
- Designed secure cloud-to-vehicle architecture enabling modular integration for upfitters.
- Developed an IoT library for secure vehicle communication, with an intrusion detection camera module as proof of concept.
{{{experience-end}}}

* Education
#+latex: \newcolumntype{Y}{>{\small\raggedright\arraybackslash}X}
#+attr_latex: :options {\linewidth}{Y Y >{}Y}
#+begin_tabularx
{{{education(Expected: May 2027,Master of Science\, Computer Science ,Georgia Institute of Technology,)}}}
{{{education(May 2022,Bachelor of Science\, Computer Science @@latex:\newline@@ Bachelor of Electrical Engineering,University of Detroit Mercy,(GPA: 3.82/4.0))}}}
#+end_tabularx

* Skills
#+attr_latex: :options {2}
#+begin_multicols
- *Languages:* Python, Rust, C, ARM Assembly, Bash, JavaScript, Haskell, MATLAB
- *Systems & Hardware:* FPGA development, microcontroller programming (Arduino, Raspberry Pi, ARM Cortex-M), embedded systems
- *Software & Tools:* Docker, Kubernetes, ROS, CI/CD, cloud platforms (GCP)
- *Specialties:* Machine learning, data mining, computer vision, algorithms, debugging complex systems
#+end_multicols

* Local Variables :noexport:
Local Variables:
eval: (add-hook 'after-save-hook 'org-latex-export-to-latex t t)
End:
