#+title: Kirols Bakheat Resume
#+author: Kirols Bakheat

#+include: ./helper.org

#+latex_header_extra: \newcommand{\githubUser}{kero0}
#+latex_header_extra: \newcommand{\linkedinUser}{kirols}
#+latex_header_extra: \newcommand{\email}{kbakheat@gmail.com}
#+latex_header_extra: \newcommand{\phone}{248-250-3241}

#+latex_header_extra: \newcommand{\header}{I am a motivated and passionate software engineer with knowledge of a wide range of areas in both computer science and hardware principles. I have experience on a breadth of areas, from developing new technologies to efficiently managing a program. I am a quick learner and have a strong desire to learn new things and to contribute with my knowledge.}

* Experience
{{{experience-start(Sensing Technologies and Algorithms FCG *|* Ford Motor Company,July 2023 -- Present)}}}
- Working to develop more accurate 3-D driver positioning for AR applications; using multiple cameras, additional sensors, and machine learning
- Working on occupant detection for safety systems
{{{experience-end}}}

{{{experience-start(Program Management FCG *|* Ford Motor Company,March 2023 -- July 2023)}}}
- Worked on launching 23MY & 24MY Super Duty trucks
- Responsible for managing diagnostic trouble codes (DTCs) and the engineers responsible for each DTC
- Helped with issue tracking and resolution
- Responsible for making sure that issues were identified and resolved before the launch
{{{experience-end}}}

{{{experience-start(Core AI/ML/QC FCG *|* Ford Motor Company,September 2022 -- February 2023)}}}
- Primary researcher into neuromorphic computing, using Intel's Loihi platform
- Designing and writing tests and gathering data to compare accuracy, efficiency, and speed against traditional computing and quantum computing
- Formulated energy-optimized routing algorithm, based on real-world Ford service, for Loihi
- Deployed service to GCP for company to provide as a service to a customer. Included writing architecture, pipeline for continuous deployment, backend, and frontend.
{{{experience-end}}}

{{{experience-start(IoT Research Intern *|* Ford Motor Company,May 2021 -- July 2021)}}}
- Wrote API microservice to serve as proof of concept for Ford's potential IoT platform
- Prototyped IoT API platform locally and on the cloud
- Designed both cloud and on-vehicle architecture and security for future generation interface for upfitters, as part of a team
- Wrote proof of concept library for securely allowing upfitter programs to communicate both with the vehicle and add in modules
- Designed and built an example module of a camera with a model for intrusion detection
{{{experience-end}}}

{{{experience-start(Digital Cockpit Technologies & Features Intern *|* Ford Motor Company,June 2020 -- July 2020)}}}
- Security research for a feature aiming to use a phone with NFC as a key for a vehicle
- Customer clinic simulation involving work in Carsim, Simulink, Qt desktop, and Qt for android
- Reviewed and developed test plans for Ford's UWB Phone-as-a-Key feature as part of a team
{{{experience-end}}}

* Education
#+begin_tabularx
#+latex: {\linewidth}{@{}l X p{0.3\hsize}}
{{{education(August 2018 -- May 2022,Bachelor of Science in Computer Science @@latex:\newline@@ Bachelor of Electrical Engineering,University of Detroit Mercy,3.82)}}}
#+end_tabularx

* Skills
#+attr_latex: :options {2}
#+begin_multicols
- Programming Languages: ARM Assembly, Bash, C, Haskell, JavaScript, MATLAB, Python, Rust
- Data mining, data analysis, and machine learning
- FPGA development
- Microcontroller development (Arduino, Raspberry Pi, ARM Cortex M)
- Robotics (ROS)
- Containerization (Docker, Kubernetes)
#+end_multicols

* Local Variables :noexport:
Local Variables:
eval: (add-hook 'after-save-hook 'org-latex-export-to-latex t t)
End:
