name: Update Docker Image
on:
  push:
    branches:
      - main
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - '.github/workflows/dockerfile.yml'

jobs:
  build:
    name: Update Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker Image
        run: nix run .#pushImage.x86_64-linux
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
