name: Build PDF

on:
  push:
    branches: [main]
    paths:
      - 'resume.org'
      - 'helper.org'
      - 'init.el'
      - '.github/workflows/main.yml'
  workflow_run:
    workflows: ["Update Docker Image"]
    types:
      - completed
jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-22.04
    container: kero18/resume-builder:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build resume
        run: ./build.sh
      - name: Rename File
        run: |
          cp resume.pdf resume-${{ github.sha }}.pdf
          mv resume.pdf Kirols-Bakheat-Resume.pdf
      - name: Release Latest
        uses: marvinpinto/action-automatic-releases@latest
        with:
          name: resume
          path: |
            Kirols-Bakheat-Resume.pdf
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Resume PDF"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: |
            resume-${{ github.sha }}.pdf
            Kirols-Bakheat-Resume.pdf
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Release-${{ github.sha }}"
          prerelease: false
          title: "Resume PDF"
