name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-x86_64-linux:
    name: Build x86_64 Linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build resume
        run: nix build
      - name: Copy artifact
        run: |
          cp result/resume.pdf resume.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: |
            resume.pdf
