name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build resume
        run: nix build
      - name: Copy artifact
        run: |
          cp result/resume.pdf resume.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: |
            resume.pdf
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          files: resume.pdf
          body: |
            New resume build
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
