name: Build PDF

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - 'resume.org'
      - 'helper.org'
      - 'helper.el'
      - '.github/workflows/main.yml'
  workflow_run:
    workflows: ["Update Docker Image"]
    types:
      - completed
jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-22.04
    container: kero18/resume-builder:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build resume
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: |
            resume.pdf
      - name: Release artifact
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: resume.pdf
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Resume"
