name: Build PDF

on:
  pull_request:
  push:
    branches: [main]
  paths:
    - 'resume.org'
    - 'helper.org'
    - 'helper.el'
    - '.github/workflows/main.yml'
    # flake.nix does not need to be included here
    # any change to flake.nix will trigger a rebuild of the environment
    # then it will necessitate a change in helper.org, which will trigger a rebuild of the PDF

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-22.04
    container: docker.io/kero18/resume-builder:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build resume
        run: ./build.sh
      - name: Copy artifact
        run: |
          cp result/resume.pdf resume.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: |
            resume.pdf
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          files: resume.pdf
          body: |
            New resume build
            Commit: ${{ github.sha }}
            Message: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
